### ISSUE TITLE
Not an issue - a Thank You instead

### ISSUE THREAD

**Issue by beegee-tokyo** [pkoerber/SMA-SunnyBoy-Reader#2]
@pkoerber
Using your library on a ESP32 to read data from my SMA Sunnyboy 2.5.

It works without any problems.

Thank you very much.

**Comment by pkoerber** [comment]
I had a strange error message for the ESP32 myself, I think a memory issue that I didn't want to investigate at the time. But good that it works for you and thank you for your message!

Paul.

**Comment by beegee-tokyo** [comment]
I am running it on an ESP32-Wrover, so I have plenty of memory, that might make the difference.
