### ISSUE TITLE
Can't compile.. ArduinoJson library?

### ISSUE THREAD

**Issue by Prutzz** [pkoerber/SMA-SunnyBoy-Reader#3]
I've loaded the sketch and the Define ArduinoJson.h stays black instead of orange?
Went to the library manager and downloaded the ArduinoJson but it still stays black. 

When I compile the sketch I'm getting an error. Any idea what might be wrong?

`C:\Users\----\Documents\Arduino\libraries\SMA-SunnyBoy-Reader-main\src\SMAReader.cpp: In member function 'bool SMAReader::postSMA(const char*, const char*, ArduinoJson6185_91::DynamicJsonDocument&)':
C:\Users\----\Documents\Arduino\libraries\SMA-SunnyBoy-Reader-main\src\SMAReader.cpp:9:15: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
    9 |     http.begin(postURL);
      |     ~~~~~~~~~~^~~~~~~~~
exit status 1
Error compiling for board Adafruit Feather HUZZAH ESP8266.`

**Comment by pkoerber** [comment]
It would indicate that my code is no longer compatible with the newest versions of the libraries. I would have to take a look at that.  I'm not sure whether ArduinoJson, or ESP8266HTTPClient is the problem. In the error message it refers to HTTPClient::begin, which is a function in the ESP8266HTTPClient library, so I think it's the latter. What you could try is install older versions of these libraries. At the time I had version 6.15.2 of ArduinoJSON. But I think ESP8266HttpClient is built in the ESP8266 board libraries, so you have to take an older version of the ESP8266 board libraries (in board manager), I had version 2.5.2.

**Comment by Prutzz** [comment]
First I downloaded your sketch again (but it seems to be the still the older one?) and didn't work.

Then I downgraded the firmware for the ESP8266 to your version and it works!! Serial shows the the wattage at the moment and the total yield for the day in w/h. Great! =)
